name = "finalprojobs360"
main = "worker.js"
compatibility_date = "2026-04-28"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
routes = [
  { pattern = "projobs360.com/*", zone_name = "projobs360.com" },
  { pattern = "www.projobs360.com/*", zone_name = "projobs360.com" }
]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "finalprojobs360-db"
database_id = "9d6bfb6d-abee-428f-88ea-e2c23a221f3f"
migrations_dir = "migrations"

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = ["/signup", "/jobs", "/jobs/*", "/payments/*", "/stripe/*"]
